version: "3"
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./tmp/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - LC_COLLATE=C
      - LC_CTYPE=C
      - LC_MESSAGES=C
      - LC_MONETARY=C
      - LC_NUMERIC=C
      - LC_TIME=C
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MYAPP_DATABASE_HOST_PATH=db
